### PR TITLE
Add OCSP-related docs

### PR DESCRIPTION
**Pull request by m-czernek**
Hi,

I am adding docs related to the OCSP SSL settings for Tomcat. What do you think?

As a side note, if this PR passes, I'd like to port the commit to higher version of Tomcats (i.e. 8 and 8.5, not yet sure about 9). However, I first want to incorporate all the feedback I get from this PR.

### CODE REVIEW

**Comment by markt-asf** [comment]
Overall, looks good. One minor nit is that line length should be limited to 80 characters for the docs.

Generally, we apply changes to the latest release (trunk/9.0.x) first and then back-port. It looks like this should apply fairly cleanly to any current Tomcat version so that shouldn't be an issue (although the Connector config will need to change).

**Comment by m-czernek** [comment]
@markt-asf my apologies for the delay. Lines are now limited to >=80 chars per line, with the exception of one line:

https://github.com/apache/tomcat70/pull/14/files#diff-7c83eaf75e758a27e08968efa65f1dc4R446

Is this acceptable? I don't think the line is strictly necessary (I have it set up for testing environment), but imho is helpful.

**Comment by markt-asf** [comment]
Thanks. Long lines in source sections are OK. I'll take a look at this in time for the next set of releases.

**Comment by markt-asf** [comment]
Patch applied to all versions.
I made a couple of minor word changes and updated the 8.5.x and 9.0.x versions to use the new TLS configuration style.

**Pull request closed without merging**
